from mininet.topo import Topo
class MyTopo( Topo ):
    def __init__(self):
        "Create a custom topology."
        Topo.__init__(self)
        host1=self.addHost('h1')
        host2 = self.addHost('h2')
        host3=self.addHost('h3')
        host4=self.addHost('h4')
        host5=self.addHost('h5')
        host6 = self.addHost('h6')
        host7 = self.addHost('h7')
        host8 = self.addHost('h8')
        host9 = self.addHost('h9')
        host10 = self.addHost('h10')
        switch1=self.addSwitch('s1')
        switch2=self.addSwitch('s2')
        switch3=self.addSwitch('s3')
        switch4 = self.addSwitch('s4')
        switch5 = self.addSwitch('s5')
        switch6 = self.addSwitch('s6')
        self.addLink(host1,switch1)
        self.addLink(host7, switch1)
        self.addLink(host8, switch1)
        self.addLink(switch1,switch2)
        self.addLink(switch2,switch3)
        self.addLink(switch3, switch4)
        self.addLink(switch2, switch5)
        self.addLink(switch2,host2)
        self.addLink(switch5,host5)
        self.addLink(switch3, host3)
        self.addLink(switch3,switch6)
        self.addLink(switch6, host6)
        self.addLink(host4,switch4)
        self.addLink(host9,switch4)
        self.addLink(host10,switch4)
topos = {'mytopo': (lambda :MyTopo())}